- Analysis/GammaGammaCandidateTruthFilter/include/GammaGammaCandidateTruthFilter.h
- Analysis/PIDTools/src/Compute_dEdxProcessor.cc
- Analysis/RecoMCTruthLink/include/RecoMCTruthLinker.h
- Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc
- SiStripDigi/source/src/SiStripClus.cc
- SiStripDigi/source/src/SiStripDigi.cc
- SiStripDigi/source/src/SiStripGeomFTD.cc
- TrackDigi/FPCCDDigi/src/FPCCDClustering.cc
- TrackDigi/FPCCDDigi/src/FPCCDDigitizer.cc
- TrackDigi/TPCDigi/src/TPCDigiProcessor.cc
- Replace ILDCellID0 to LCTrackerCellID
> Replace ILDCellID0 to LCTrackerCellID

- Analysis/CLICPfoSelector/include/CLICDstChecker.h
- Analysis/CLICPfoSelector/include/CLICPfoSelector.h
- Analysis/CLICPfoSelector/src/CLICDstChecker.cc
- Analysis/CLICPfoSelector/src/CLICPfoSelector.cc
- CMakeLists.txt
- Re-enable compilation of CLICPfoSelector, CLICDstChecker
- Fix Warnings in  CLICPfoSelector, CLICDstChecker
> enable Clicpfoselector again

- TrackDigi/TPCDigi/src/TPCDigiProcessor.cc
- update resolution formula in TPC digitisation (from Dimitra Tsionou)
> update TPC resolution formula

- CaloDigi/Realistic/src/BruteForceEcalGapFiller.cc
- BruteForceEcalGapFiller : Add missing information on calo hit type
> BruteForceEcalGapFiller : Add missing information on calo hit type

- CaloDigi/SDHCALDigi/include/SimDigital.h
- CaloDigi/SDHCALDigi/src/SimDigital.cc
- improve SDHCALDigi/src/SimDigital.cc
- Fixed the exception of unknown name y
- add optional parameter HCALCellSize to overwrite the one from dd4hep
> Fixed the issue of exception

- CaloDigi/SDHCALDigi/include/SimDigital.h
- Drop unused and no longer existing header includes AidaSoft/DD4hep#241
> Remove includes of removed files

- Analysis/PIDTools/include/Compute_dEdxProcessor.hh
- Analysis/PIDTools/src/Compute_dEdxProcessor.cc
- Analysis/PIDTools/src/CreatePDFProcessor.cc
- Analysis/PIDTools/src/LikelihoodPID.cc
- improved PIDTools
- added additional smearing functon for dE/dx resolution.
- and corrected the strange behavior for PID. That is most of the muons are identified as pions.
> add smearing function and correct PID

- CaloDigi/SDHCALDigi/include/ChargeInducer.h
- CaloDigi/SDHCALDigi/include/ChargeSpreader.h
- CaloDigi/SDHCALDigi/include/EfficiencyManager.h
- CaloDigi/SDHCALDigi/include/SimDigital.h
- CaloDigi/SDHCALDigi/include/SimDigitalGeom.h
- CaloDigi/SDHCALDigi/include/SimDigitalLinkToParticles.h
- CaloDigi/SDHCALDigi/include/SimDigitalToEnergy.h
- CaloDigi/SDHCALDigi/src/ChargeInducer.cc
- CaloDigi/SDHCALDigi/src/ChargeSpreader.cc
- CaloDigi/SDHCALDigi/src/EfficiencyManager.cc
- CaloDigi/SDHCALDigi/src/SimDigital.cc
- CaloDigi/SDHCALDigi/src/SimDigitalGeom.cc
- CaloDigi/SDHCALDigi/src/SimDigitalLinkToParticles.cc
- CaloDigi/SDHCALDigi/src/SimDigitalToEnergy.cc
- New SDHCAL digitizer version from Lyon group (ggarillot)
- step linking
- two processors, one for applying the threshold, one for the threshold energy factors
> New SDHCAL digitizer version

- Analysis/IsolatedLeptonFinder/include/IsolatedLeptonFinderProcessor.h
- cmake/clang-cpp-checks.cmake
> Fix coverity scan

- Analysis/SiPID/include/LayerFinder.h
- Analysis/SiPID/src/LayerFinder.cc
- Analysis/TruthVertexFinder/src/MCOperator.cc
> Addop for LCIO cleaning

- Analysis/PIDTools/include/Compute_dEdxProcessor.hh
- Analysis/PIDTools/src/Compute_dEdxProcessor.cc
- Compute_dEdXProcessor:
- geometry issue: gear to DD4hep unit adaption, fixed low momentum problem
- added dx calculation strategies
- added various processor options, default are all old version
- added documentation
> update dEdx processor: geomtry issue for low momentum; new dx strategies

- CaloDigi/SDHCALDigi/include/ChargeSpreader.h
- CaloDigi/SDHCALDigi/include/SimDigital.h
- CaloDigi/SDHCALDigi/include/SimDigitalLinkToParticles.h
- CaloDigi/SDHCALDigi/src/ChargeSpreader.cc
- CaloDigi/SDHCALDigi/src/SimDigital.cc
- CaloDigi/SDHCALDigi/src/SimDigitalLinkToParticles.cc
fixes #47 
- SDHCAL digitizer : 
- Switch order of the LCRelation collection between SDHCAL SimCalorimeterHits and Digitized CalorimeterHits (now from CalorimeterHit to SimCalorimeterHit)
> Fix Digitized SDHCAL hits LCRelation collection

- CMakeLists.txt
- TimeOfFlight/README.md
- TimeOfFlight/example/tofplots_steer.xml
- TimeOfFlight/include/TOFEstimators.h
- TimeOfFlight/include/TOFPlots.h
- TimeOfFlight/include/TOFUtils.h
- TimeOfFlight/scripts/draw_cluster_time.C
- TimeOfFlight/scripts/draw_tofestimators.C
- TimeOfFlight/scripts/lcio_particle_gun.py
- TimeOfFlight/scripts/make_root_plots.sh
- TimeOfFlight/scripts/run_all_and_make_root_plots_random.sh
- TimeOfFlight/scripts/run_all_marlin.sh
- TimeOfFlight/scripts/run_all_marlin_10GeV.sh
- TimeOfFlight/scripts/run_all_marlin_2GeV.sh
- TimeOfFlight/scripts/run_all_marlin_5GeV.sh
- TimeOfFlight/scripts/run_all_marlin_v1.sh
- TimeOfFlight/scripts/run_all_marlin_v2.sh
- TimeOfFlight/scripts/tofestimators.xml
- TimeOfFlight/src/TOFEstimators.cc
- TimeOfFlight/src/TOFPlots.cc
- TimeOfFlight/src/TOFUtils.cc
- add new package TimeOfFlight
- use TOFEstimators processor to compute TOF parameters
- will be added as PID object to the ReconstructedParticles
> WIP: Add tof

- Analysis/GammaGammaHadronRemoval/README.md
- Analysis/GammaGammaHadronRemoval/example/findTrackGroups.xml
- Analysis/GammaGammaHadronRemoval/include/TrackZVertexGrouping.h
- Analysis/GammaGammaHadronRemoval/src/TrackZVertexGrouping.cc
- CMakeLists.txt
- add sub-package Analysis/GammaGammaHadronRemoval
- first processor *TrackZVertexGrouping* implementation of track grouping based on Z0 significance
- algorithm developed by S.Sasikumar, DESY
> Track grouping

- Analysis/CLICPfoSelector/src/CLICPfoSelectorAnalysis.cc
- CLICPfoSelectorAnalysis: Fix entries of time vs pt
> Fix entries of time vs pt plot

- Analysis/PIDTools/include/ReconstructedParticleImpl_CopyProcessor.h
- Analysis/PIDTools/src/ReconstructedParticleImpl_CopyProcessor.cc
- Add ReconstructedParticleImpl_CopyProcessor
> Add Reco_CopyProc

- Analysis/IsolatedLeptonTagging/README
- Analysis/IsolatedLeptonTagging/example/isolated_electron_weights_woIP
- Analysis/IsolatedLeptonTagging/example/isolated_muon_weights_woIP_woYoke
- Analysis/IsolatedLeptonTagging/example/isolated_muon_weights_woYoke
- Analysis/IsolatedLeptonTagging/example/isolep_woIP_woYoke.xml
- Analysis/IsolatedLeptonTagging/include/IsolatedLeptonTaggingProcessor.h
- Analysis/IsolatedLeptonTagging/src/IsolatedLeptonTaggingProcessor.cc
- Analysis/IsolatedLeptonTagging/weights/yyxyev_yyxyyx_woIP_500.mILD_l5_o1_v02/TMVAClassification_MLP.weights.xml
- Analysis/IsolatedLeptonTagging/weights/yyxylv_yyxyyx_woIP_woYoke_500.mILD_l5_o1_v02/TMVAClassification_MLP.weights.xml
- added fix to IsolatedLeptonfinder
- added a new feature for supporting applications not using impact parameters
- added corresponding weight files trained for the new feature
> Iso lep fix

- Analysis/TrueJet/include/TrueJet.h
- Analysis/TrueJet/src/TrueJet.cc
- TrueJet: 
- Much improved assignment of PFOs to jets, and hence of seen jet energies
- Get rid of all -Wall warnings
> Truejet update

- Analysis/AddClusterProperties/src/AddClusterProperties.cc
- Analysis/RecoMCTruthLink/src/QuarkJetPairing.cc
- Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc
- Analysis/TrueJet/src/TrueJet.cc
- CaloDigi/SDHCALDigi/src/SimDigital.cc
- Replaced raw usage of streamlog by pre-processor macros from streamlog package
> Fixed usage of streamlog 

- Analysis/PhotonEnergyCorrect/include/photonCorrectionProcessor.h
- Analysis/PhotonEnergyCorrect/include/photonCorrector.h
- Analysis/PhotonEnergyCorrect/src/photonCorrectionProcessor.cc
- Analysis/PhotonEnergyCorrect/src/photonCorrector.cc
- remove hard-coded default correction; control everything from processor parameters.
- add getter and print functionality to PhotonCorrector class
> photon correction code improvements

- Analysis/IsolatedLeptonTagging/include/IsoLepTrainingProcessor.h
- Analysis/IsolatedLeptonTagging/src/IsoLepTrainingProcessor.cc
- Analysis/IsolatedLeptonTagging/training/TMVAClassification.C
- added a processor which can be used to obtain the needed input variables for MVA training of IsolatedLeptonTagging
- added a root macro of MVA Classification for the training. 
> added training code

- Analysis/IsolatedLeptonTagging/include/Utilities.h
- Analysis/IsolatedLeptonTagging/src/IsoLepTrainingProcessor.cc
- Analysis/IsolatedLeptonTagging/src/Utilities.cc
- add a new processor which can be used to obtain the input variables for isolated lepton training
- add a MVA Classification macro for training
> Iso lep training

- Analysis/IsolatedLeptonTagging/README
- Analysis/IsolatedLeptonTagging/example/isolep.xml
- Analysis/IsolatedLeptonTagging/include/IsolatedPhotonTaggingProcessor.h
- Analysis/IsolatedLeptonTagging/include/Utilities.h
- Analysis/IsolatedLeptonTagging/src/IsolatedLeptonTaggingProcessor.cc
- Analysis/IsolatedLeptonTagging/src/IsolatedPhotonTaggingProcessor.cc
- Analysis/IsolatedLeptonTagging/src/Utilities.cc
- added a new processor for finding isolated photon
- the default option for isolated muon finder is changed back to use Yoke energy
> added a new processor for finding isolated photon

- Tracking/KinkFinder/src/KinkFinder.cc
- Make the KinkFinder always produce all output collections even if some of them are empty
> Make the KinkFinder always produce all output collections even if some of them are empty

- CaloDigi/Realistic/src/RealisticCaloDigi.cc
- Add a missing `#include <algorithm>`
Fix https://github.com/iLCSoft/MarlinReco/issues/138.
> Add a missing include <algorithm>

- Analysis/PhotonEnergyCorrect/scripts/README.md
- Analysis/PhotonEnergyCorrect/scripts/extractCorrection.py
- Analysis/PhotonEnergyCorrect/scripts/prepareInput.py
- Add code needed to obtain the photon energy and direction corrections which are used in the photonCorrectionProcessor (as promised in https://github.com/iLCSoft/MarlinReco/issues/144#issuecomment-2576491059 )
> code to calculate photon PFO corrections
