iLCSoft/MarlinReco

Analysis/RecoMCTruthLink/include/RecoMCTruthLinker.h
Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc

- RecoMCTruthLinker: move encoder initialisation from constructor to function body to avoid accessing encoding_string too early

Move encoder initialisation into function

---

Clustering/PhotonFinderKit/src/EMShowerFinder.cc
Clustering/PhotonFinderKit/src/KIT.cc
TrackDigi/VTXDigi/src/CCDDigitizer.cc
TrackDigi/VTXDigi/src/VTXDigitizer.cc
TrackDigi/VTXDigi/src/VTXNoiseClusters.cc

- removed deprecated SimTrackerHit::setCellID
- don't use assignment for CellIDDecoder
- update to latest changes in LCIO
- removed deprecated SimTrackerHit::setCellID
- don't use assignment for CellIDDecoder

update to latest changes in LCIO

---

Analysis/CLICPfoSelector/include/CLICDstChecker.h
Analysis/CLICPfoSelector/include/CLICPfoSelector.h
Analysis/CLICPfoSelector/include/PfoUtilities.h
Analysis/CLICPfoSelector/src/CLICDstChecker.cc
Analysis/CLICPfoSelector/src/CLICPfoSelector.cc
Analysis/TauFinder/src/EvaluateTauFinder.cc
Analysis/TauFinder/src/PrepareRECParticles.cc
Analysis/TauFinder/src/TauFinder.cc

Needs ilcsoft/MarlinUtil#4
- CLICPfoSelector: remove dependency on GEAR File; simplify calculation of TimeAtECal by using trackState at Calorimeter
- CLICPfoSelector: fix coverity defect
- TauFinder: fix coverity defects; use streamlog instead of cout

Fixes and improvements for CLICPfoSelector/TauFinder

---

Analysis/TauFinder/src/PrepareRECParticles.cc
Analysis/TauFinder/src/TauFinder.cc

- read magnetic field from dd4hep in taufinder particle preparator
- remove leftover condition for former printout of the taufinder, which prevents the desired increment of the iterator, and thus deletes wrong taucandidates when filling the reconstructed tau's 

read parameters from dd4hep, fix iterator in tau candidate quality loop

---

CMakeLists.txt

- Set default from 'ON' to 'OFF' to build MarlinReco fortran sources.
- It could be switch on in the release-ilcsoft.cfg if you want.
- https://github.com/iLCSoft/iLCInstall/blob/master/releases/HEAD/release-ilcsoft.cfg#L116

 Set default from 'ON' to 'OFF' to build MarlinReco fortran sources.

---

Analysis/TauFinder/src/PrepareRECParticles.cc
Tracking/V0Finder/src/V0Finder.cc

These give tiny memory leaks spotted by valgrind, and also prevent configuration...
Should we add an exception in Marlin if two parameters have the same name?
- TauFinder:: PrepareRecParticles: change second parameter with same name RecCollection --> RecCollection_Tracks
- V0Finder: Change second parameter to its correct Name RxyCutGamma --> RxyCutLambda

Fix duplicate parameters

---

Analysis/RecoMCTruthLink/include/RecoMCTruthLinker.h
Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc

- RecoMCTruthLinker: clean collections that are only created for linking. Move cleanup to end of process event instead of trackLinker so things are also cleaned up if there are no tracks. Fixes memory leaks

RecoMCTruthLinker: cleanup of transient collections

---

Analysis/TauFinder/src/TauFinder.cc

delete ReconstructedParticleImpl object if it fails cuts and is not added to vector to be treated later
Move adding of relationships after we know whether to keep the particle or not so we do not have dangling pointer in the relationships
- TauFinder: fix memory leak (few kB/event)

TauFinder: fix memory leak

---

CaloDigi/Realistic/include/BruteForceEcalGapFiller.h
CaloDigi/Realistic/src/BruteForceEcalGapFiller.cc

- modify algorithm to fill ECAL gaps in BruteForceEcalGapFiller:
- overall linear suppression gap hit energies [as was done in DBD]
- additional logarithmic suppression to reduce large energy gap hits
- separate parameters for (a) gaps between modules, and (b) gaps within modules
- default values of new parameters seem reasonable for ILD_l4_v02 model

modify ECAL gap filling method

---

Analysis/PIDTools/include/Compute_dEdxProcessor.hh
Analysis/PIDTools/src/Compute_dEdxProcessor.cc

- Missing memory allocation and delete for random engine
- Added delete specification for copy constructor and assignment operator to avoid warning on compilation
- Missing delete for two arrays causing memory leaks  

dEdX processor fix

---

Analysis/SiPID/include/AnalyseSidEdxProcessor.h
Analysis/SiPID/include/LayerFinder.h
Analysis/SiPID/include/SiTracker_dEdxProcessor.h
Analysis/SiPID/src/AnalyseSidEdxProcessor.cc
Analysis/SiPID/src/LayerFinder.cc
Analysis/SiPID/src/SiTracker_dEdxProcessor.cc
Analysis/SiPID/xml/AnaSidEdx.xml
Analysis/SiPID/xml/SiTrack_dEdx.xml

Updates of SiTracker_dEdxProcessor:
- Cleaned up unnecessary code.
- Added runtime protection against failure of `TrackImpl::getTrackState()`.
- Replaced `MarlinTrk::IMarlinTrack::propagate()` which was making the processor ~1000X slower than necessary with `MarlinTrk::IMarlinTrack::extrapolate()`.
- Removed unnecessary parameters.
Updates of AnalyseSidEdxProcessor:
-   Added minor runtime protections.

SiPID: fresh update

---

.clang-format
Analysis/IsolatedLeptonFinder/README
Analysis/IsolatedLeptonFinder/example/steer.xml
Analysis/IsolatedLeptonFinder/include/IsolatedLeptonFinderProcessor.h
Analysis/IsolatedLeptonFinder/src/IsolatedLeptonFinderProcessor.cc
CMakeLists.txt
README.md
cmake/clang-cpp-checks.cmake

This addition to the IsolatedLeptonFinderProcessor dresses electrons with close-by photons. It is currently under development and this PR serves as baseline for discussion.
- This package is an extension to the IsolatedLeptonFinderProcessor. The default functionality is untouched.
- Optionally, it dresses leptons with close-by particles. By default it dresses electrons and muons with photons.
- The algorithm starts with the highest energy lepton and adds all photons (and, optionally, electrons) in a cone of a given size around to it. As the original, it creates a collection with the dressed leptons and another collections with all remaining particles, except the ones that were dressed into the leptons.
- All compiler warnings are fixed

Dress electrons in IsolatedLeptonFinder

---

Analysis/IsolatedLeptonTagging/src/IsolatedLeptonTaggingProcessor.cc

- IsolatedLeptonTaggingProcessor processor:
- Fixed processor logic when PFO or Vertex input collections don't exist or are empty
Fixes #56

IsolatedLeptonTaggingProcessor fix for empty/absent input collections

---

Clustering/hybridEcalSplitter/include/DDStripSplitter.h
Clustering/hybridEcalSplitter/readme.txt
Clustering/hybridEcalSplitter/src/DDStripSplitter.cc

- add new Marlin processor DDStripSplitter, which implements the Strip Splitting Algorithm for eg a scintillator strip ECAL.

strip splitting for new ILD models based on dd4hep geometry

---

Analysis/PIDTools/include/ReconstructedParticleImpl_CopyProcessor.h
Analysis/PIDTools/src/ReconstructedParticleImpl_CopyProcessor.cc

- ReconstructedParticleImpl_CopyProcessor:
- Added relation collection to link old PFOs to new PFOs

ReconstructedParticleImpl_CopyProcessor: relation collection

---

CaloDigi/LDCCaloDigi/src/SimpleFCalDigi.cc

- SimpleFcalDigi processor:
- Missing cellid 1 flag in fcal output collection, causing issues in the BeamCal reconstruction

SimpleFcalDigi fix (cellID1)

---

Analysis/ErrorFlow/include/ErrorFlow.h
Analysis/ErrorFlow/src/ErrorFlow.cc
CMakeLists.txt

- Remove compiler warnings for ErrorFlow processor (default initialization in header, using shared_ptr instead of raw pointer).
- Add ErrorFlow processor to list of processors to be compiled by default in MarlinReco.

Default-compile ErrorFlow processor in MarlinReco

---

Analysis/ErrorFlow/include/ErrorFlow.h
Analysis/ErrorFlow/src/ErrorFlow.cc

- An option is added to include full CovMat of neutral PFOs in jet error

Add option to include full CovMat of neutrals

---

Analysis/TrueJet/README.md
Analysis/TrueJet/examples/truejet_run_ana_onthefly.xml
Analysis/TrueJet/include/TrueJet.h
Analysis/TrueJet/src/TrueJet.cc
Analysis/TrueJet_Parser/README.md
Analysis/TrueJet_Parser/examples/Use_TrueJet/src/Use_TrueJet.cc
Analysis/TrueJet_Parser/include/TrueJet_Parser.h
Analysis/TrueJet_Parser/src/TrueJet_Parser.cc

Heavily reworked version of TrueJet
===========================
From the outside, little has changed:
New jet-type (6) for non-isr photon from the hard interaction.
Does not require recoparticles (nor recomctruthlink), so also works
on generator-output lcio-files.
Boolean steering flag to indicate Whizard1 (GDE) or Whizard2 (LCC) input
(false by default, i.e. input is Whizard2)
Internally, heavily re-worked.
- removed methods fix94 and fix_top
- New method (stdhep_reader_bug_workaround) called if _whiz1 is true  
- New method - photon - added to treat the new jet type 6 (M.E. photon).
- New boolean data-members _whiz1 (steering flag),  _higgs_to_glue_glue
and _top_event (the latter two set at run-time event by event)
- Handle the case if no reconstructed information …

Full true jet update

---

TimeOfFlight/include/TOFEstimators.h
TimeOfFlight/scripts/tofestimators.xml
TimeOfFlight/src/TOFEstimators.cc

- TOFEstimators processor: adding new algorithms to calculate the ToF, track length and momentum.
- New output parameters:
- TOFClosest --- based on the closest ECAL hit
- TOFFastest --- based on the fastest ECAL hit
- TOFCylFit --- extrapolated time from the ECAL hits within a cylinder of a shower core
- TOFClosestFit --- extrapolated time from the ECAL hits closest to the linear continuation of the track inside the ECAL
- FlightLength --- the helix track length based on the track parameters from the TrackState at the ECAL
- MomAtCal --- the momentum based on the track parameters from the TrackState at the ECAL
- New steering parameters:
- ProcessorVersion --- changes output between the idr version (before this patch) and the dev (after this patch). Default: idr
- …

Addition of new algorithms to TOFEstimator processor

---

CaloDigi/Realistic/doc/Readme_ROCTiming.md
CaloDigi/Realistic/include/RealisticCaloDigi.h
CaloDigi/Realistic/include/RealisticCaloDigiScinPpd.h
CaloDigi/Realistic/include/RealisticCaloDigiSilicon.h
CaloDigi/Realistic/src/RealisticCaloDigi.cc
CaloDigi/Realistic/src/RealisticCaloDigiScinPpd.cc
CaloDigi/Realistic/src/RealisticCaloDigiSilicon.cc

- RealisticCaloDigi: Added new option for energy/charge and time integration
- deal with slow/fast shaper of ROC chips and time estimate
- new processor parameters:
- **integrationMethod**: "Standard" for old implementation (default) or "ROC" emulating the behavior of ROC chip.
- **fastShaper**: fast shaper time, unit in ns. Only for ROC method
- **slowShaper**: slow shaper time, unit in ns. Only for ROC method
- **timingResolution**: optional time resolution gaussian smearing to apply, unit . Only apply is > 0. Default is 0 (no smearing)
Fixes #41 
Parameter values for ROC implementation:
- AHCAL
- **fastShaper** = 15 ns
- **slowShaper** =  50 ns
- **timingResolution** = 700 ps
- SiWECal
- **fastShaper** = 90 ns (first estimate)
- **slowShaper** =  180 …

RealisticCaloDigi: new ROC integration

---

Analysis/PIDTools/include/AngularCorrection_dEdxProcessor.hh
Analysis/PIDTools/include/Compute_dEdxProcessor2021.hh
Analysis/PIDTools/include/LikelihoodPID.hh
Analysis/PIDTools/include/LikelihoodPIDProcessor.hh
Analysis/PIDTools/src/AngularCorrection_dEdxProcessor.cc
Analysis/PIDTools/src/Compute_dEdxProcessor2021.cc
Analysis/PIDTools/src/LikelihoodPID.cc
Analysis/PIDTools/src/LikelihoodPIDProcessor.cc
Analysis/PIDTools/steer/DSTcorrection_dEdx_and_LikelihoodPID.xml
doc/ReleaseNotes.md

Pull request for the dEdxAngular correction issues discussed in https://agenda.linearcollider.org/event/9197/
Related to Issue #90 
The ee-> bb/cc/ss (250GeV) analysis team ( @airqui  @yuichiok) have validated the steering files and processor and checked that the dEdx performance is recovered
@tmadlener @gaede 
Note: I did modify manually the ReleaseNotes.md file in my private branch... I am not sure if the information will be double-written or not.
- PIDTools: 
- LikelihoodPID modified to be able to accept as arguments the name and type of method to run and store (allowing for versioning)
- AngularCorrection_dEdxProcessor created to use with DST samples generated with v02-02 and v02-02-01. The dEdx is corrected for angular effects.
- Compute_dEdxProcessor2021, …

Featured edx angularcorr

---

Tracking/KinkFinder/src/KinkFinder.cc

- apply the correct units for TPC parameters from DD4hep
- fixes #97
-  apply correct units for VXD and SIT layers
-   need cross check of efficiency for kink finding 
-  (how could this have worked before ?)

fix units in TPC parameters

---

Analysis/IsolatedLeptonTagging/include/IsolatedLeptonTaggingProcessor.h
Analysis/IsolatedLeptonTagging/src/IsolatedLeptonTaggingProcessor.cc
Analysis/IsolatedLeptonTagging/src/IsolatedPhotonTaggingProcessor.cc
Analysis/TauFinder/src/TaJetClustering.cc

- Make the IsolatedLeptonTagging processor always produce the expected output collections, even for empty input collections, i.e. if the inputs are empty:
- the `OutputPFOsWithoutIsoLepCollection` will simply have the same content as the `InputPandoraPFOsCollection`
-  the `OutputIsoLeptonsCollection` will be empty. 
- On the other hand actually missing input collections will now no longer be handled as these point to a real problem (e.g. typo in the collection name). Fixes #93

IsolatedLeptonTagging: Always fill expected output collections if inputs are empty

---

TimeOfFlight/src/TOFEstimators.cc
TimeOfFlight/src/TOFUtils.cc

- Try to fit subtrack forward if backward fit fails
- Fix seg. fault if the very first sub track fit fails in both directions
- Change behaviour of checking track direction. Now it is more robust and relies on z position of first and last hits.
This is the fix for #102 with some improved behaviour on how do we check what is the direction of subTrack.
Previous behaviour:
- check position of the last hit from previous iteration `prevHit`
- check **linear** distance between `prevHit` and two edge hits of current iteration.
- choose closest one to be continuation of the prev. subtrack.
Playing with event display has shown it doesn't always work with curly tracks. 
As it may curl in and out of the inner TPC edge so some hits will disappear and the last hit …

Fix seg fault when fit fails and improve subTrack direction check based on z

---

.github/workflows/coverity.yml
.github/workflows/key4hep.yml
.github/workflows/linux.yml

- Remove no longer available CI workflow based on gcc8 since the underlying nightly builds are no longer available
- Update github actions to latest available versions

Remove no longer available CI workflow based on gcc8

---

Tracking/TrackLength/src/TrackLengthProcessor.cc
Tracking/TrackLength/src/TrackLengthUtils.cc

- Fix a seg. fault, in rare cases, when the track fit fails in both directions due to the lack of hits.
Found out that around 2.2% of my jobs seg. faulted because of that. Few cases, which i encountered, had tracks with 3-6 hits in total.
I am not sure, how the track successfully created in the first place, as I have tried to keep fit procedure as similar to the production code as possible.

hot fix seg. fault when there is not enough hits to calculate the track length

---

Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc

- Make encoding RecoParticle relation weights more explicit with a new encode function in MarlinUtil

Encode RecoParticle relation weights more explicit

---

Analysis/OverlayRemoval/example/CheatedMCOverlayRemoval.xml
Analysis/OverlayRemoval/include/CheatedMCOverlayRemoval.h
Analysis/OverlayRemoval/src/CheatedMCOverlayRemoval.cc

Added CheatedMCOverlayRemoval processor to identify MC particles that are overlay and remove the corresponding PFOs from the collection. See under example for how to run processor

Added processor for cheating away overlay

---

TimeOfFlight/include/TOFEstimators.h
TimeOfFlight/include/TOFUtils.h
TimeOfFlight/src/TOFEstimators.cc
TimeOfFlight/src/TOFUtils.cc

- Always use the first (before)  --> latest (now) curl in the track to get extrapolated track position at the calorimeter surface. This gives sometimes better estimate of the track position at the ECAL surface, especially for the tracks with large number of curls. Thus  new version gives better time of flight correction for the distance to the surface and thus TOF itself.
- Minor style improvements

Update of the time of flight processor

---

Tracking/TrackLength/include/TrackLengthUtils.h
Tracking/TrackLength/src/TrackLengthProcessor.cc
Tracking/TrackLength/src/TrackLengthUtils.cc

- Switch to the helix formula without Omega: $\ell_{i} = \frac{|z_{i+1} - z_{i}|}{|\tan{\lambda_{i}}|}\sqrt{1 +\tan^2{\lambda_{i}}}$. It shows the best performance so far.
- Other bug fixes and consistency improvements.
+ The most major change is the new formula to calculate the helical distance between two neighboring track states.
We change from $\ell_{i} = \sqrt{\left( \frac{\varphi_{i+1} - \varphi_{i}}{\Omega_{i}}\right)^{2} + \left( z_{i+1} - z_{i} \right)^{2} }$ to $\ell_{i} = \frac{|z_{i+1} - z_{i}|}{|\tan{\lambda_{i}}|}\sqrt{1 +\tan^2{\lambda_{i}}}$ as it shows much more precise results for all tracks.
+ Fixed a bug where the track state at the calorimeter surface was not included when track fit of the last subTrack has failed. Now we extrapolate …

Update of the Track length calculator

---

CaloDigi/SDHCALDigi/include/SimDigital.h
CaloDigi/SDHCALDigi/include/SimDigitalGeom.h
CaloDigi/SDHCALDigi/src/SimDigital.cc
CaloDigi/SDHCALDigi/src/SimDigitalGeom.cc

- Switch from `dd4hep::long64` to `dd4hep::CellID` to be compatible with DD4hep after [AIDASoft/DD4hep#1125](https://github.com/AIDASoft/DD4hep/pull/1125)

Fix usage of dd4hep::long64 to dd4hep::CellID

---

TimeOfFlight/src/TOFEstimators.cc
TimeOfFlight/src/TOFUtils.cc

- In case of the option to measure time-of-flight at the SET: now using raw (digitized strips) SET hits instead of simulated hits. It doesn't change anything now, but could become trouble in the future when proper time digitization is added.

Use digitized (not sim) SET hits for time-of-flight measurement

---

CaloDigi/LDCCaloDigi/src/SimpleFCalDigi.cc

- Populate the type information for the output relation collection in the `SimpleFCalDigi`
- Fix some warnings there as well. (Fixes [#100](https://github.com/iLCSoft/MarlinReco/issues/100))

Fill relation type information in FCal digitizer

---

Analysis/LeptonID/include/LeptonIDProcessor.h
Analysis/LeptonID/src/LeptonIDProcessor.cc
Analysis/PIDTools/include/ComprehensivePIDProcessor.h
Analysis/PIDTools/src/AlgorithmMgr.cc
Analysis/PIDTools/src/ComprehensivePIDProcessor.cc
Analysis/PIDTools/src/InputAlgorithm_TOF.cc
Analysis/PIDTools/src/ModelMgr.cc

Minor changes in CPID:
- allow for no automatic creation of root file or plots
- if no output root file and no training then no intermediate TTree is filled
- add efficiency numbers on additional confusion matrix plot
- in TOF algorithm use mass² instead of beta
LeptonID: Remove inheritance from EventModifier

CPID and LeptonID update

---

Tracking/KinkFinder/src/KinkFinder.cc

- Fixed PDG code for kinks identifies as antiSigma+

Fixed sign of PDG value for antiSigma+

---

Analysis/TrueJet/include/TrueJet.h
Analysis/TrueJet/src/TrueJet.cc

- Make the `TrueJet` processor use the `PIDHandler` to set the `ParticleIDs` for the different objects it creates. This sets the necessary metadata that is required, e.g. for the conversion to EDM4hep. 
Fixes key4hep/k4EDM4hep2LcioConv#62
@Zehvogel can you check whether this fixes things on your end? At least from a technical level, the algorithm names might still need some tuning, but I would also be interested to see which ones are actually hit / converted.

Make the TrueJet processor use the PIDHandler to set the ParticleIDs 

---

Analysis/PIDTools/include/ReconstructedParticleParticleIDFilterProcessor.h
Analysis/PIDTools/src/ReconstructedParticleParticleIDFilterProcessor.cc
Analysis/PIDTools/steer/FilterParticleID.xml

- Add a `ReconstructedParticleParticleIDFilterProcessor` that allows to filter `ParticleID` objects from existing `ReconstructedParticle`s.
This is necessary for an upcoming miniDST production and allows the further abuse of `ParticleID` as transport mechanism of potentially transient information between Marlin processors.

Add a processor for filtering ParticleIDs from ReconstructedParticles

---

.github/workflows/key4hep.yml

- Remove CentOS7 from the Key4hep CI workflows

Remove centos7 from Key4hep CI

---

PFOID/src/CreatePDFs.cc

- Fix `mismateched-new-delete` warning uncovered by gcc14 (see [#140](https://github.com/iLCSoft/MarlinReco/issues/140))
Fixes #140 
Lifted from #141

Fix new warnings uncovered by gcc14

---

.github/workflows/key4hep.yml

- Switch to latest available nightlies and releases for Key4hep based CI workflows
- Add `workflow_dispatch` trigger and scheduled runs every week

Switch to newer nightlies and releases for Key4hep CI
